single-title:
  front_matter_title: ''
ul-style: false
ul-indent:
  indent: 2
ol-prefix: false
line-length:
  line_length: 808
no-trailing-punctuation: false
no-inline-html: false
no-emphasis-as-heading: false
blank_lines: false
