name: release-preview

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release-preview:
    needs: test
    uses: ./.github/workflows/release.yml
    with:
      environment: next
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_TOKEN }}

  release-stable-update-branch:
    runs-on: ubuntu-latest
    needs: release-preview
    steps:
      - uses: actions/checkout@v3
        # can't use the secrets.GITHUB_TOKEN since this doesn't trigger further workflows
        # https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/9
        with:
          token: ${{ secrets.GH_REPO_PAT }}
      - run: |
          git branch -D stable || echo "branch not found, continuing anyway"
          git checkout -b stable
          git push -f origin stable
