name: release-stable

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    uses: ./.github/workflows/release.yml
    with:
      environment: stable
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_TOKEN }}

  docs:
    uses: ./.github/workflows/docs.yml
    needs: release
    with:
      deploy: true
      version: ${{ needs.release.outputs.version }}
