name: test

on:
  workflow_call:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
      - run: dotnet tool restore
      - run: dotnet build /p:TreatWarningsAsErrors=true
      - run: dotnet format --no-restore --verify-no-changes
      - run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - uses: codecov/codecov-action@v1
